export const mySkills = [
  "Teamwork",
  "Time management",
  "JavaScript",
  "React",
  "React Router",
  "Redux (Toolkit)",
  "Redux-Saga",
  "React Hooks",
  "Redux Hooks",
  "Working with API (axios, fetch)",
  "Promises, Async/Await",
  "Local Storage",
  "Custom Hooks",
  "Styled Components",
  "Error handling",
  "HTML",
  "Responsive Web Design",
  "CSS BEM convenction",
  "CSS Grid",
  "CSS Flex",
  "Media Queries",
  "Immutability",
  "Git",
  "NPM",
  "GitHub Pull Requests & Review",
  "Trello",
  "Jira",
  "Scrum",
];

export const toLearn = [
  "TypeScript",
  "Next.js",
  "Node.js",
  "Unit Testing",
  "JS classes",
  "Wordpress",
  "Tailwind CSS",
];
